/**
 * @file usbstack_config.h
 * @brief a header file for TZ10xx USB Stack configuration
 * @version V0.0
 * @date $Date:: 2014-10-03 16:48:52 +0900 #$
 * @note
 */

/*
 * COPYRIGHT (C) 2014
 * TOSHIBA CORPORATION SEMICONDUCTOR & STORAGE PRODUCTS COMPANY
 * ALL RIGHTS RESERVED
 *
 * THE SOURCE CODE AND ITS RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA
 * CORPORATION MAKES NO OTHER WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR,
 * STATUTORY AND DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
 * SATISFACTORY QUALITY, NON INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
 * 
 * THE SOURCE CODE AND DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION
 * RESERVES THE RIGHT TO INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER
 * REVISIONS OF IT, AND TO MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR
 * THE PRODUCTS OR TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME.
 * 
 * TOSHIBA CORPORATION SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT OR
 * CONSEQUENTIAL DAMAGE OR LIABILITY ARISING FROM YOUR USE OF THE SOURCE CODE OR
 * ANY DOCUMENTATION, INCLUDING BUT NOT LIMITED TO, LOST REVENUES, DATA OR
 * PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL NATURE, PUNITIVE
 * DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS ARISING OUT OF OR IN CONNECTION
 * WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF ADVISED OF THE POSSIBILITY OR
 * PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM FOR SUCH DAMAGE IS BASED UPON
 * WARRANTY, CONTRACT, TORT, NEGLIGENCE OR OTHERWISE.
 */
#ifndef USBSTACK_CONFIG_H
#define USBSTACK_CONFIG_H

/**
  @brief GPIO pin configuration for VBus detection
*/
#include "GPIO_TZ10xx.h"
#define USC_GPIO_VBUS_PIN   0
#define USC_GPIO_VBUS_DIR   GPIO_DIRECTION_INPUT_HI_Z
#define USC_GPIO_VBUS_EVENT GPIO_EVENT_EDGE_BOTH

/**
  @brief DeviceDescriptor, bMaxPacketSize0 field
*/
#include "RTE_Device.h"
#define USC_MAXPACKETSIZE0  RTE_USB2FS_MPS0
#define USC_NUM_EPS         RTE_USB2FS_NUM_EPS

/**
  @brief Workaround for the specific host.
*/

// 1=enable 0=disable
#define USC_RECONNECT_ON_TIMEOUT 0

#if USC_RECONNECT_ON_TIMEOUT
// Unit : msec
#define USC_RECONNECT_ON_TIMEOUT_DELAY 100
// =0 ~ <TIMER_NUM_MAX
#define USC_RECONNECT_ON_TIMEOUT_TIMER 1
// 1=enable 0=disable
#define USC_RECONNECT_ON_TIMEOUT_TEST 0
#endif


#endif /* USBSTACK_CONFIG_H */
